name: planner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  calendar_timeline: ^1.1.2
  cloud_firestore: ^4.13.6
  dartz: ^0.10.1
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  fluttericon: ^2.0.0
  get: ^4.6.6
  google_sign_in: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  tuple: ^2.0.2
  uuid: ^4.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Sans Serif
      fonts:
        - asset: assets/fonts/Wanafi.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
